from enum import Enum
    
class Sosial_Kependudukan(Enum):
    GENDER = "https://sumut.bps.go.id/subject/40/gender.html#subjekViewTab3"
    GEOGRAFI = "https://sumut.bps.go.id/subject/153/geografi.html#subjekViewTab3"
    IKLIM = "https://sumut.bps.go.id/subject/151/iklim.html#subjekViewTab3"
    INDEKS_PEMBANGUNAN_MANUSIA = "https://sumut.bps.go.id/subject/26/indeks-pembangunan-manusia.html#subjekViewTab3"
    KEMISKINAN_DAN_KETIMPANGAN = "https://sumut.bps.go.id/subject/23/kemiskinan-dan-ketimpangan.html#subjekViewTab3"
    KEPENDUDUKAN = "https://sumut.bps.go.id/subject/12/kependudukan.html#subjekViewTab3"
    KESEHATAN = "https://sumut.bps.go.id/subject/30/kesehatan.html#subjekViewTab3"
    KONSUMSI_DAN_PENGELUARAN = "https://sumut.bps.go.id/subject/5/konsumsi-dan-pengeluaran.html#subjekViewTab3"
    LINGKUNGAN_HIDUP = "https://sumut.bps.go.id/subject/152/lingkungan-hidup.html#subjekViewTab3"
    PEMERINTAHAN = "https://sumut.bps.go.id/subject/101/pemerintahan.html#subjekViewTab3"
    PENDIDIKAN = "https://sumut.bps.go.id/subject/28/pendidikan.html#subjekViewTab3"
    PERUMAHAN = "https://sumut.bps.go.id/subject/29/perumahan.html#subjekViewTab3"
    POLITIK_DAN_KEAMANAN = "https://sumut.bps.go.id/subject/34/politik-dan-keamanan.html#subjekViewTab3"
    POTENSI_DESA = "https://sumut.bps.go.id/subject/168/potensi-desa.html#subjekViewTab3"
    SOSIAL_BUDAYA = "https://sumut.bps.go.id/subject/27/sosial-budaya.html#subjekViewTab3"
    TENAGA_KERJA = "https://sumut.bps.go.id/subject/6/tenaga-kerja.html#subjekViewTab3"

class Ekonomi_Perdagangan(Enum):
    EKSPOR_IMPOR = "https://sumut.bps.go.id/subject/8/ekspor-impor.html#subjekViewTab3"
    ENERGI = "https://sumut.bps.go.id/subject/7/energi.html#subjekViewTab3"
    HARGA_ECERAN = "https://sumut.bps.go.id/subject/102/harga-eceran.html#subjekViewTab3"
    HARGA_PERDAGANGAN_BESAR = "https://sumut.bps.go.id/subject/20/harga-perdagangan-besar.html#subjekViewTab3"
    HARGA_PRODUSEN = "https://sumut.bps.go.id/subject/36/harga-produsen.html#subjekViewTab3"
    INDUSTRI_BESAR_DAN_SEDANG = "https://sumut.bps.go.id/subject/9/industri-besar-dan-sedang.html#subjekViewTab3"
    INDUSTRI_MIKRO_DAN_KECIL = "https://sumut.bps.go.id/subject/170/industri-mikro-dan-kecil.html#subjekViewTab3"
    INFLASI = "https://sumut.bps.go.id/subject/3/inflasi.html#subjekViewTab3"
    INPUT_OUTPUT = "https://sumut.bps.go.id/subject/105/input-output.html#subjekViewTab3"
    ITB_ITK = "https://sumut.bps.go.id/subject/25/itb-itk.html#subjekViewTab3"
    KEUANGAN = "https://sumut.bps.go.id/subject/13/keuangan.html#subjekViewTab3"
    KOMUNIKASI = "https://sumut.bps.go.id/subject/2/komunikasi.html#subjekViewTab3"
    KONSTRUKSI = "https://sumut.bps.go.id/subject/4/konstruksi.html#subjekViewTab3"
    MATRIK_INVESTASI = "https://sumut.bps.go.id/subject/179/matrik-investasi.html#subjekViewTab3"
    NERACA_ARUS_DANA = "https://sumut.bps.go.id/subject/100/neraca-arus-dana.html#subjekViewTab3"
    NERACA_INSTITUSI_TERINTEGRASI = "https://sumut.bps.go.id/subject/178/neraca-institusi-terintegrasi.html#subjekViewTab3"
    NERACA_SOSIAL_EKONOMI = "https://sumut.bps.go.id/subject/104/neraca-sosial-ekonomi.html#subjekViewTab3"
    NILAI_TUKAR_PETANI = "https://sumut.bps.go.id/subject/22/nilai-tukar-petani.html#subjekViewTab3"
    PARIWISATA = "https://sumut.bps.go.id/subject/16/pariwisata.html#subjekViewTab3"
    PERDAGANGAN_DALAM_NEGERI = "https://sumut.bps.go.id/subject/173/perdagangan-dalam-negeri.html#subjekViewTab3"
    PRODUK_DOMESTIK_BRUTO_LAPANGAN_USAHA = "https://sumut.bps.go.id/subject/11/produk-domestik-bruto--lapangan-usaha-.html#subjekViewTab3"
    PRODUK_DOMESTIK_BRUTO_PENGELUARAN = "https://sumut.bps.go.id/subject/169/produk-domestik-bruto--pengeluaran-.html#subjekViewTab3"
    PRODUK_DOMESTIK_REGIONAL_BRUTO_LAPANGAN_USAHA = "https://sumut.bps.go.id/subject/52/produk-domestik-regional-bruto--lapangan-usaha-.html#subjekViewTab3"
    PRODUK_DOMESTIK_REGIONAL_BRUTO_PENGELUARAN = "https://sumut.bps.go.id/subject/171/produk-domestik-regional-bruto--pengeluaran-.html#subjekViewTab3"
    TRANSPORTASI = "https://sumut.bps.go.id/subject/17/transportasi.html#subjekViewTab3"
    UPAH_BURUH = "https://sumut.bps.go.id/subject/19/upah-buruh.html#subjekViewTab3"
    USAHA_MIKRO_KECIL = "https://sumut.bps.go.id/subject/35/usaha-mikro-kecil.html#subjekViewTab3"


class Pertanian_Pertambangan(Enum):
    HORTIKULTURA = "https://sumut.bps.go.id/subject/55/hortikultura.html#subjekViewTab3" 
    KEHUTANAN = "https://sumut.bps.go.id/subject/60/kehutanan.html#subjekViewTab3" 
    PERIKANAN = "https://sumut.bps.go.id/subject/56/perikanan.html#subjekViewTab3" 
    PERKEBUNAN = "https://sumut.bps.go.id/subject/54/perkebunan.html#subjekViewTab3" 
    PERTAMBANGAN = "https://sumut.bps.go.id/subject/10/pertambangan.html#subjekViewTab3" 
    PETERNAKAN = "https://sumut.bps.go.id/subject/24/peternakan.html#subjekViewTab3" 
    TANAMAN_PANGAN = "https://sumut.bps.go.id/subject/53/tanaman-pangan.html#subjekViewTab3" 


